### PR TITLE
This will resolve splunk login connectivity

### PR DESCRIPTION
**Pull request by hrish11**
Currently using this Splunk pack we are facing login authentication issue, by passing additional parameter autologin=True it will connect more than once with passed credentials & provide us successful connection

### CODE REVIEW

**Comment by satellite-no** [comment]
Is this going to be merged in?

**Comment by hrish11** [comment]
yes

**Review by armab — CHANGES_REQUESTED** [review]
Thanks for the PR!

Could you please update the Changelog and pack.yaml with the version update?
Patch version bump would be the most appropriate.

**Comment by armab** [comment]
Looks like the pack doesn't have a Maintainer, outside of the TSC.

@hrish11 @satellite-no  If you're using this pack in prod and would like to maintain this pack, - please let us know in this PR.
This would include reviewing the incoming PRs, collaborating around the incoming Issues, and overall ensuring if the pack works (which is already true if you're using it).

**Comment by satellite-no** [comment]
I'd be glad to helpout the community.  I had some features for this pack I wanted to try and give back anyway so it works lol.

**Comment by armab** [comment]
Sounds good, @satellite-no.

Could you please compose a PR in `splunk` pack with Codeowners and Readme.md changes, as described in the https://github.com/StackStorm-Exchange/exchange-incubator/issues/152#issuecomment-737565528 ?

**Comment by satellite-no** [comment]
Done

**Comment by satellite-no** [comment]
Closing due to inactivity and the changes suggested have diverged.

**Pull request closed without merging**
